# Generated by Django 2.2.4 on 2020-11-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PythonExamApp', '0002_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='plan',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
